# Previsao por Media Movel Simples por Slot (15 min)

Notebook de previsao mensal por `slot_15m` para a `ESCOLA_MUNICIPAL`, com comparacao entre modelos e visualizacao dos resultados.

Este notebook foca no **fluxo de previsao**.

In [27]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

## Parametros

Ajuste os parametros abaixo para definir periodo, edificio e janela da SMA.

- `TARGET_YEAR` e `TARGET_MONTH`: mes de referencia da analise.
- `SMA_FORECAST_YEAR`: ano usado na previsao mes a mes.
- `SMA_SLOT_WINDOW` e `SMA_SLOT_MIN_PERIODS`: configuracao da media movel por slot de 15 min.
- `SMA_TRAIN_LOOKBACK_DAYS`: quantos dias anteriores entram no treino da SMA.

In [28]:
TARGET_YEAR = 2025
TARGET_MONTH = 10
SMA_FORECAST_YEAR = 2025

BUILDING_FILTER = "ESCOLA_MUNICIPAL"
TARGET_COL = "consumption_kwh"
BUILDING_COL = "building"

INPUT_CSV = "https://raw.githubusercontent.com/lucasmedss/peca/main/cg_public_energy_consumption.csv"

SMA_SLOT_WINDOW = 21
SMA_SLOT_MIN_PERIODS = 14
SMA_TRAIN_LOOKBACK_DAYS = 21  # None ou <=0 usa historico completo
USE_FIRST_WEEK = True
FIRST_WEEK_DAYS = 7

MESES_PT = {
    1: "Jan", 2: "Fev", 3: "Mar", 4: "Abr",
    5: "Mai", 6: "Jun", 7: "Jul", 8: "Ago",
    9: "Set", 10: "Out", 11: "Nov", 12: "Dez"
}

In [29]:
def load_history(
    dataframe: pd.DataFrame,
    target_col: str,
    building_col: str = "building",
    building_filter: str | None = None,
) -> pd.DataFrame:

    df = dataframe.copy()

    if building_col not in df.columns and "building_id" in df.columns:
        df[building_col] = df["building_id"]

    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df[target_col] = pd.to_numeric(df[target_col], errors="coerce")
    df = df.dropna(subset=["timestamp", target_col])

    if building_filter is not None:
        filtro = str(building_filter).strip()
        df = df[df[building_col].astype(str).str.strip() == filtro]

    history = (
        df.sort_values("timestamp")
        .set_index("timestamp")[target_col]
        .resample("15min")
        .sum(min_count=1)
        .to_frame(name=target_col)
        .dropna()
    )
    return history


def month_range(year: int, month: int) -> pd.DatetimeIndex:
    start = pd.Timestamp(year=year, month=month, day=1)
    end = (start + pd.offsets.MonthEnd(1)).normalize() + pd.Timedelta(hours=23, minutes=45)
    return pd.date_range(start=start, end=end, freq="15min")


def select_history_window(history: pd.DataFrame, lookback_days: int | None):
    if lookback_days is None:
        return history.copy()
    lookback_days = int(lookback_days)
    if lookback_days <= 0:
        return history.copy()
    cutoff = history.index.max() - pd.Timedelta(days=lookback_days)
    return history.loc[history.index >= cutoff].copy()

## Fluxo da Previsao

O fluxo principal e:
1. Carregar e limpar historico de consumo.
2. Construir previsao por `slot_15m` com SMA.
3. Agregar para total mensal previsto x real.
4. Comparar versoes do modelo (SMA normal e sazonal ajustado).
5. Visualizar os resultados em graficos.

## Modelo Utilizado e Estratégia de Avaliação

O modelo principal é uma **Média Móvel Simples (SMA) por slot de 15 minutos**.

Como o dia tem 24 horas e cada hora tem 4 intervalos de 15 minutos, cada dia possui **96 slots** (`slot_15m` de 0 a 95).

Neste notebook, a previsão usa apenas `slot_15m` como referência histórica (mesmo horário do dia). Em seguida, a série prevista em 15 minutos é agregada para total mensal.

A avaliação foi conduzida por **backtest temporal**:
1. Escolhe-se um mês alvo.
2. Usa-se apenas dados anteriores ao início desse mês para treinar a SMA (sem vazamento de informação futura).
3. Gera-se a previsão completa do mês em resolução de 15 minutos.
4. Agrega-se para consumo mensal e compara-se com o valor real do mesmo mês.

Exemplo intuitivo:
Para prever o consumo de **10:15**, o modelo usa a média móvel das observações históricas desse mesmo slot de horário (10:15).

In [30]:
df_raw = pd.read_csv(INPUT_CSV, parse_dates=["timestamp"])
history = load_history(df_raw, TARGET_COL, BUILDING_COL, BUILDING_FILTER)

forecast_start = pd.Timestamp(year=SMA_FORECAST_YEAR, month=TARGET_MONTH, day=1)

history_before_month = history.loc[
    history.index < forecast_start
]

first_week_end = forecast_start + pd.Timedelta(days=FIRST_WEEK_DAYS)

first_week_data = history.loc[
    (history.index >= forecast_start)
    & (history.index < first_week_end)
]

history_until_month = pd.concat([
    history_before_month,
    first_week_data
]).sort_index()

hist_slot = select_history_window(history_until_month, SMA_TRAIN_LOOKBACK_DAYS)
hist_slot["slot_15m"] = hist_slot.index.hour * 4 + (hist_slot.index.minute // 15)

hist_slot["sma_slot"] = hist_slot.groupby("slot_15m")[TARGET_COL].transform(
    lambda s: s.rolling(window=SMA_SLOT_WINDOW, min_periods=SMA_SLOT_MIN_PERIODS).mean()
)

next_pred_per_slot = hist_slot.groupby("slot_15m")["sma_slot"].last()
fallback_mean = (
    float(hist_slot["sma_slot"].dropna().mean())
    if hist_slot["sma_slot"].notna().any()
    else float(hist_slot[TARGET_COL].mean())
)

print(f"Periodo de treino da SMA: {hist_slot.index.min()} ate {hist_slot.index.max()} ({len(hist_slot)} pontos de 15 min) | lookback_dias={SMA_TRAIN_LOOKBACK_DAYS}")
print(f"Janela SMA por slot: {SMA_SLOT_WINDOW} observacoes | min_periods={SMA_SLOT_MIN_PERIODS}")

Periodo de treino da SMA: 2025-09-16 23:45:00 ate 2025-10-07 23:45:00 (2017 pontos de 15 min) | lookback_dias=21
Janela SMA por slot: 21 observacoes | min_periods=14

In [31]:
def forecast_idx_sma_slot(future_idx: pd.DatetimeIndex, slot_predictions: pd.Series, fallback: float) -> pd.DataFrame:
    future = pd.DataFrame(index=future_idx)
    future["slot_15m"] = future.index.hour * 4 + (future.index.minute // 15)
    future["consumption_kwh_pred_sma_slot"] = future["slot_15m"].map(slot_predictions).fillna(fallback).astype(float)
    return future[["consumption_kwh_pred_sma_slot"]]

month_full = month_range(SMA_FORECAST_YEAR, TARGET_MONTH)

future_idx = month_full[
    month_full >= first_week_end
]
forecast_sma_slot = forecast_idx_sma_slot(future_idx, next_pred_per_slot, fallback_mean)

print(f"Periodo previsto (mes alvo): {future_idx.min()} ate {future_idx.max()}")
print(f"Total previsto no mes alvo (kWh): {forecast_sma_slot['consumption_kwh_pred_sma_slot'].sum():,.2f}")
display(forecast_sma_slot.head(680))

Periodo previsto (mes alvo): 2025-10-08 00:00:00 ate 2025-10-31 23:45:00
Total previsto no mes alvo (kWh): 1,139.48

                     consumption_kwh_pred_sma_slot
2025-10-08 00:00:00                       0.365890
2025-10-08 00:15:00                       0.362757
2025-10-08 00:30:00                       0.359093
2025-10-08 00:45:00                       0.361812
2025-10-08 01:00:00                       0.356350
...                                            ...
2025-10-15 00:45:00                       0.361812
2025-10-15 01:00:00                       0.356350
2025-10-15 01:15:00                       0.357909
2025-10-15 01:30:00                       0.361405
2025-10-15 01:45:00                       0.362664

[680 rows x 1 columns]

In [32]:
# =============================
# Avaliação mês a mês
# =============================

resultados = []

for mes in range(1, 13):

    forecast_start = pd.Timestamp(year=SMA_FORECAST_YEAR, month=mes, day=1)

    history_until_month = history.loc[history.index < forecast_start]

    hist_slot = select_history_window(history_until_month, SMA_TRAIN_LOOKBACK_DAYS)

    if hist_slot.empty:
        continue

    hist_slot = hist_slot.copy()

    hist_slot["slot_15m"] = (
        hist_slot.index.hour * 4
        + (hist_slot.index.minute // 15)
    )

    # SMA por slot recalculada para cada mês
    hist_slot["sma_slot"] = hist_slot.groupby("slot_15m")[TARGET_COL].transform(
        lambda s: s.rolling(
            window=SMA_SLOT_WINDOW,
            min_periods=SMA_SLOT_MIN_PERIODS
        ).mean()
    )

    next_pred_per_slot = hist_slot.groupby("slot_15m")["sma_slot"].last()

    fallback_mean = (
        float(hist_slot["sma_slot"].dropna().mean())
        if hist_slot["sma_slot"].notna().any()
        else float(hist_slot[TARGET_COL].mean())
    )

    future_idx = month_range(SMA_FORECAST_YEAR, mes)

    forecast = forecast_idx_sma_slot(
        future_idx,
        next_pred_per_slot,
        fallback_mean
    )

    previsto_mes = forecast["consumption_kwh_pred_sma_slot"].sum()

    actual = history.loc[
        future_idx.min():future_idx.max(),
        [TARGET_COL]
    ]

    real_mes = (
        actual[TARGET_COL].sum()
        if not actual.empty else None
    )

    resultados.append({
        "Mes_num": mes,
        "Previsto_SMA_Slot": previsto_mes,
        "Real": real_mes,
        "Diferenca_kWh": (
            previsto_mes - real_mes
            if real_mes is not None else None
        )
    })


df_sma_compare = pd.DataFrame(resultados)

df_sma_compare["Mes"] = df_sma_compare["Mes_num"].map(MESES_PT)

display(
    df_sma_compare[
        ["Mes", "Real", "Previsto_SMA_Slot", "Diferenca_kWh"]
    ].round(2)
)

    Mes     Real  Previsto_SMA_Slot  Diferenca_kWh
0   Jan   949.52            1020.46          70.94
1   Fev  1324.74             925.77        -398.97
2   Mar  1604.51            1610.84           6.33
3   Abr  1668.56            1687.68          19.11
4   Mai  1711.78            1714.33           2.55
5   Jun  1263.92            1692.74         428.82
6   Jul  1458.96            1185.13        -273.82
7   Ago  1344.15            1403.86          59.70
8   Set  1418.07            1350.54         -67.53
9   Out  1391.03            1481.73          90.70
10  Nov  1295.91            1332.25          36.35
11  Dez  1114.42            1361.06         246.64

In [33]:
ano_analise = SMA_FORECAST_YEAR

# Garantir ordenação correta
df_plot = df_sma_compare.sort_values("Mes_num").copy()

# ==============================
# GRÁFICO REAL vs PREVISTO (SMA)
# ==============================

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_plot["Mes"],
    y=df_plot["Real"],
    mode="lines+markers",
    name="Consumo Real",
    line=dict(color="#3b82f6", width=3),
    fill="tozeroy",
    fillcolor="rgba(59, 130, 246, 0.1)"
))

fig.add_trace(go.Scatter(
    x=df_plot["Mes"],
    y=df_plot["Previsto_SMA_Slot"],
    mode="lines+markers",
    name="Previsão SMA",
    line=dict(color="#ef4444", width=3, dash="dot"),
    marker=dict(symbol="x", size=8)
))

fig.update_layout(
    title=f"<b>Análise Anual ({ano_analise}): Real vs. SMA</b><br><sup>Edificação: {BUILDING_FILTER}</sup>",
    xaxis_title="Mês do Ano",
    yaxis_title="Consumo Total Mensal (kWh)",
    plot_bgcolor="white",
    hovermode="x unified",
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

fig.update_yaxes(
    gridcolor="whitesmoke",
    tickformat=","
)

fig.update_xaxes(showgrid=False)

fig.show()

In [36]:
# ============================================
# MODELO SAZONAL AJUSTADO COM PRIMEIRA SEMANA REAL
# ============================================

MESES_SAZONAIS = {2, 6, 7, 12}
ANO_BASE = SMA_FORECAST_YEAR - 1
FIRST_WEEK_DAYS = 7

resultados = []

for mes in range(1, 13):

    future_idx = month_range(SMA_FORECAST_YEAR, mes)

    # REAL COMPLETO DO MÊS
    actual_full = history.loc[
        future_idx.min():future_idx.max(),
        [TARGET_COL]
    ]

    real_mes = actual_full[TARGET_COL].sum() if not actual_full.empty else None


    # =========================
    # SMA NORMAL
    # =========================

    forecast_start = pd.Timestamp(year=SMA_FORECAST_YEAR, month=mes, day=1)
    history_until_month = history.loc[history.index < forecast_start]

    hist_slot = select_history_window(history_until_month, SMA_TRAIN_LOOKBACK_DAYS)

    if hist_slot.empty:
        continue

    hist_slot = hist_slot.copy()
    hist_slot["slot_15m"] = (
        hist_slot.index.hour * 4 +
        (hist_slot.index.minute // 15)
    )

    hist_slot["sma_slot"] = hist_slot.groupby("slot_15m")[TARGET_COL].transform(
        lambda s: s.rolling(
            window=SMA_SLOT_WINDOW,
            min_periods=SMA_SLOT_MIN_PERIODS
        ).mean()
    )

    next_pred = hist_slot.groupby("slot_15m")["sma_slot"].last()
    fallback = float(hist_slot[TARGET_COL].mean())

    forecast_sma = forecast_idx_sma_slot(
        future_idx,
        next_pred,
        fallback
    )

    previsto_sma = forecast_sma["consumption_kwh_pred_sma_slot"].sum()


    # =========================
    # MODELO SAZONAL AJUSTADO
    # =========================

    if mes in MESES_SAZONAIS:

        # PRIMEIRA SEMANA REAL
        first_week_end = future_idx.min() + pd.Timedelta(days=FIRST_WEEK_DAYS)
        real_first_week = history.loc[
            future_idx.min():first_week_end,
            [TARGET_COL]
        ]

        consumo_primeira_semana = (
            real_first_week[TARGET_COL].sum()
            if not real_first_week.empty else 0
        )

        # RESTANTE DO MÊS (PREVISÃO)
        restante_idx = future_idx[future_idx >= first_week_end]

        base_idx = month_range(ANO_BASE, mes)
        base_data = history.loc[
            base_idx.min():base_idx.max(),
            [TARGET_COL]
        ]

        if not base_data.empty:

            base_data = base_data.copy()
            base_data["slot_15m"] = (
                base_data.index.hour * 4 +
                (base_data.index.minute // 15)
            )

            perfil_mes = (
                base_data
                .groupby("slot_15m")[TARGET_COL]
                .mean()
            )

            forecast_temp = pd.DataFrame(index=restante_idx)
            forecast_temp["slot_15m"] = (
                forecast_temp.index.hour * 4 +
                (forecast_temp.index.minute // 15)
            )

            forecast_temp["pred"] = (
                forecast_temp["slot_15m"]
                .map(perfil_mes)
                .fillna(perfil_mes.mean())
            )

            consumo_restante = forecast_temp["pred"].sum()

        else:
            consumo_restante = 0

        previsto_sazonal = consumo_primeira_semana + consumo_restante

    else:
        previsto_sazonal = previsto_sma


    resultados.append({
        "Mes_num": mes,
        "Real": real_mes,
        "SMA_Normal": previsto_sma,
        "Sazonal_Ajustado": previsto_sazonal
    })


df_compare = pd.DataFrame(resultados)
df_compare["Mes"] = df_compare["Mes_num"].map(MESES_PT)
df_compare = df_compare.sort_values("Mes_num")

display(df_compare.round(2))

    Mes_num     Real  SMA_Normal  Sazonal_Ajustado  Mes
0         1   949.52     1020.46           1020.46  Jan
1         2  1324.74      925.77           1148.00  Fev
2         3  1604.51     1610.84           1610.84  Mar
3         4  1668.56     1687.68           1687.68  Abr
4         5  1711.78     1714.33           1714.33  Mai
5         6  1263.92     1692.74           1211.27  Jun
6         7  1458.96     1185.13           1388.45  Jul
7         8  1344.15     1403.86           1403.86  Ago
8         9  1418.07     1350.54           1350.54  Set
9        10  1391.03     1481.73           1481.73  Out
10       11  1295.91     1332.25           1332.25  Nov
11       12  1114.42     1361.06           1169.97  Dez

In [37]:
fig = go.Figure()

# REAL
fig.add_trace(go.Scatter(
    x=df_compare["Mes"],
    y=df_compare["Real"],
    mode="lines+markers",
    name="Consumo Real",
    line=dict(width=3)
))

# SMA NORMAL
fig.add_trace(go.Scatter(
    x=df_compare["Mes"],
    y=df_compare["SMA_Normal"],
    mode="lines+markers",
    name="SMA Original",
    line=dict(dash="dot", width=3)
))

# SAZONAL AJUSTADO
fig.add_trace(go.Scatter(
    x=df_compare["Mes"],
    y=df_compare["Sazonal_Ajustado"],
    mode="lines+markers",
    name="SMA com Sazonalidade",
    line=dict(dash="dash", width=3)
))

fig.update_layout(
    title=f"Modelo Sazonal Ajustado — Escola Municipal",
    xaxis_title="Mês",
    yaxis_title="Consumo Total Mensal (kWh)",
    plot_bgcolor="white",
    hovermode="x unified",
    legend=dict(
        orientation="h",
        y=1.1,
        x=0.5,
        xanchor="center"
    )
)

fig.update_yaxes(gridcolor="whitesmoke", tickformat=",")
fig.update_xaxes(showgrid=False)

fig.show()

## Saidas Esperadas

Ao final, este notebook entrega:
- Tabela mensal com consumo real e previsto por modelo.
- Grafico anual comparando Real, SMA Original e SMA com Sazonalidade.